#!/bin/bash

dir="labs"
link="html"
page="index.html"
user="ntobeko"

echo "NGINX CONFIG SCRIPT"
echo "###################"
echo "script starting..."
sleep 1
if [ systemctl is-active nginx ]
then
         echo "service running, continuing with configuration..."
         sleep 1
         echo "creating directory $dir""
         sleep 1
         mkdir /var/www/html/$dir
         if [ -d /var/www/html/$dir ]
         then
                 echo "changing ownership of $dir to $user"
         else
                 echo "did not find directory /var/www/html/$dir"
                 echo "exiting script"
                 exit 1
         fi
         sleep 1
         chown $user:root /var/www/html/labs
         echo "creating symbolic link $link"
         sleep 1
         ln -s /var/www/html/$link $home/$link
         sleep 1
         if [ -L $home/$link ]
         then
                echo "creating test page $page"
                touch $page
                echo "adding dummy content to $page"
                sleep 1
                echo "<html>" >>$page
                echo "<body>" >>$page
                echo "<h1>" >>$page
                echo "Welcome to Operating Systems 2" >>$page
                echo "</h1>" >>$page
                echo "</body>" >>$page
                echo "</html>" >>$page
                cat ../html/$page
                echo "script has finished executing on 'date'"
         else
                echo "symbolic link ($link) was not found!"
                echo "script will now exit..."
                sleep 1
                exit
         fi
else
         echo "nginx service not running"
         echo "exiting script"
        exit 1
fi

#end of script

Declaration
$sudo./webserver_config_script.bash
